---
title: "XOLAIR Logistic Regression"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(aod)
library(ggplot2)
```

```{r}
xol_pref <- read_excel("DATA FOR LOGIT - XOLAIR Asthma Physician ATU 04132020 CS.xlsx")
View(xol_pref)
```

```{r}
#descriptive statistics

summary(xol_pref)
sapply(xol_pref, sd)

#check to make sure that there aren't any 0 cells

xtabs(~PreferenceX + Segment + CAT_Bucket + Specialty + Region, data = xol_pref)
```

```{r}
#conversion to factor to treat variables as categorical

xol_pref$Segment <- factor(xol_pref$Segment)
xol_pref$CAT_Bucket <- factor(xol_pref$CAT_Bucket)
xol_pref$Region <- factor(xol_pref$Region)
xol_pref$Specialty <- factor(xol_pref$Specialty)

#initial logistic regression

xol_logit <- glm(PreferenceX ~ Segment + CAT_Bucket + Region + Specialty, data = xol_pref, family = "binomial")
```

```{r}
#regression output

summary(xol_logit)
```

It seems that region does not have any influence on XOLAIR preference and will likely negatively influence model fit. Lets remove and reassess.

```{r}
#second logistic model

xol_logit2 <- glm(PreferenceX ~ Segment + CAT_Bucket + Specialty, data = xol_pref, family = "binomial")

#logistic regression output
summary(xol_logit2)
```

```{r}
#assessing model fit
#CIs using profiled log-likelihood

confint(xol_logit2)
```

```{r}
#statistical test to determint the overall effect of Segment, therefore, used "Terms = (2:4)" from the list of beta values in the model above

wald.test(b = coef(xol_logit2), Sigma = vcov(xol_logit2), Terms = (2:4))
```

```{r}
#additional hypothesis testing for the individual segments
#multiply the terms of the model above by +1 and -1 that we want to test; multiple all other coefficients by 0
#Segment 2 vs Segment 3 below

S2_3 <- cbind(0, 1, -1, 0, 0, 0, 0)
wald.test(b = coef(xol_logit2), Sigma = vcov(xol_logit2), L = S2_3)

#Segment 2 vs Segment 4 below

S2_4 <- cbind(0, 1, 0, -1, 0, 0, 0)
wald.test(b = coef(xol_logit2), Sigma = vcov(xol_logit2), L = S2_4)

#Segment 3 vs Segment 4 below

S3_4 <- cbind(0, 0, 1, -1, 0, 0, 0)
wald.test(b = coef(xol_logit2), Sigma = vcov(xol_logit2), L = S3_4)
```

```{r}
#statistical test to determint the overall effect of CAT_Bucket, therefore, used "Terms = (5:6)" from the list of beta values in the model above

wald.test(b = coef(xol_logit2), Sigma = vcov(xol_logit2), Terms = (5:6))
```

```{r}
#additional hypothesis testing for the individual CAT_buckets
#multiply the terms of the model above by +1 and -1 that we want to test; multiple all other coefficients by 0
#CAT_Bucket 2 vs CAT_Bucket 3 below

C2_3 <- cbind(0, 0, 0, 0, 1, -1, 0)
wald.test(b = coef(xol_logit2), Sigma = vcov(xol_logit2), L = C2_3)
```

```{r}
#Interpretability; better to interpret as odds ratios instead of log odds

exp(coef(xol_logit2))

#odds ratios for CIs

exp(cbind(OR = coef(xol_logit2), confint(xol_logit2)))
```

```{r}
#considering predicted probabilities (using categorical variables as ordinal)

new_xol_pref <- with(xol_pref, data.frame(Segment = factor(1:4), CAT_Bucket = factor(1:3), Specialty = mean(Specialty)))
```